# fly.toml app configuration file generated for mat-links on 2023-06-20T02:27:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mat-links"
primary_region = "waw"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
